spring:
  profiles:
    default: local
  application:
    name: open-api-gateway
  cloud:
    gateway:
      routes:
        - id: backend-products
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/products/**
        - id: backend-orders
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/orders/**
        - id: backend-claims
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/claims/**
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9001

openapi:
  gateway:
    jwks-uri: http://localhost:9002/oauth/.well-known/jwks.json
    expected-issuer: http://localhost:9002

logging:
  level:
    org.example.openapi: DEBUG
    AUDIT: INFO
